sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker restart

script:
  - cd scope-swarm-launcher && docker build -t stefanprodan/scope-swarm-launcher:$TRAVIS_BUILD_NUMBER .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker tag stefanprodan/scope-swarm-launcher:$TRAVIS_BUILD_NUMBER stefanprodan/scope-swarm-launcher:latest;
    docker push stefanprodan/scope-swarm-launcher:latest;
    fi
